#!/bin/bash
# DO NOT REMOVE SHEBANG

# This script is used to check your tests. For python files, leave this file empty
# All paths are relative to '.debug/<environment>/testing'

# Here are the most popular options that you can use:

# python3 /path/to/your/checker.py