#!/bin/bash
# DO NOT REMOVE SHEBANG

# This script is used to compile your code. For python files, leave this file empty
# All paths are relative to '.debug/<environment>/testing'

# Here are the most popular options that you can use:

# clang++ -std=c++23 file.cpp
# g++ -std=c++23 /path/to/your/file.cpp